name: React App Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Set Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "youremail@example.com"

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          npx gh-pages -d build --repo "https://${{ github.actor}}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
